#   coding=utf-8
# 加盟商登录、补仓、退仓操作
import time
from selenium import webdriver
# 正常账号密码商城登录验证
# 添加提交补仓单
driver=webdriver.Firefox()
driver.get("http://192.168.1.251:9527/login")
driver.find_element_by_xpath(".//*[@id='uid']").send_keys("15090658127")
driver.find_element_by_xpath(".//*[@id='pwd']").send_keys("658127")
time.sleep(1)
driver.find_element_by_xpath(".//*[@id='login_submit_button']").click()
driver.find_element_by_xpath(".//*[@id='app_sidebar']/ul/li[4]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='stock_good_list']/tbody/tr/td[14]/button[2]").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='margin_quantity']").send_keys("10")
driver.find_element_by_xpath(".//*[@id='modal_submit']").click()
driver.find_element_by_xpath(".//*[@id='alert_modal_close']").click()
time.sleep(5)
driver.find_element_by_xpath(".//*[@id='app_header']/div/div[3]/div[1]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='margin_arrive_time']").click()
time.sleep(3)
driver.find_element_by_xpath("html/body/div[6]/div[3]/table/tbody/tr[6]/td[7]").click()
time.sleep(3)
driver.find_element_by_xpath("html/body/div[6]/div[2]/table/tbody/tr/td/span[24]").click()
time.sleep(3)
driver.find_element_by_xpath("html/body/div[6]/div[1]/table/tbody/tr/td/span[12]").click()
driver.find_element_by_xpath(".//*[@id='margin_deliveryman_name']").send_keys("李松")
driver.find_element_by_xpath(".//*[@id='margin_deliveryman_phone']").send_keys("15090658127")
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='cart_margin_table']/thead/tr/th[1]/input").click()
driver.find_element_by_xpath(".//*[@id='margin_submit_button']").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='modal_submit']").click()
# 登录仓库输入系统、审核预约单、入库操作
driver.get("http://192.168.1.243:48000/users/login")
driver.find_element_by_xpath("html/body/div[1]/div[2]/div/form/div/input[1]").send_keys("13111111111")
driver.find_element_by_xpath(".//*[@id='password']").send_keys("123456")
driver.find_element_by_xpath("html/body/div[1]/div[2]/div/form/input").click()
time.sleep(3)
driver.find_element_by_id("supplierUserCityName").find_elements_by_tag_name("option")[1].click()
driver.find_element_by_xpath(".//*[@id='alert-modal']/div/div/div[3]/span[2]").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='side-menu']/li[2]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='752']/li[3]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='759']/li[1]/a").click()
time.sleep(3)
# 获取预约单号
bc_id=driver.find_element_by_xpath(".//*[@id='list_views_table']/tbody/tr/td[2]").text
print(bc_id)
driver.find_element_by_xpath(".//*[@id='list_views_table']/tbody/tr/td[7]/span").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='stock-in-apply-detail-modal']/div[3]/input").send_keys("李松测试")
driver.find_element_by_xpath(".//*[@id='complete-confirm']").click()
time.sleep(10)
driver.find_element_by_xpath(".//*[@id='752']/li[1]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='753']/li[1]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='order-receiver-input']").send_keys("wxs001")
driver.find_element_by_xpath(".//*[@id='order-receiver-input-confirm']").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='order-receiver-input']").send_keys(bc_id)
driver.find_element_by_xpath(".//*[@id='order-receiver-input-confirm']").click()
driver.find_element_by_xpath(".//*[@id='order-receipt-confirm']").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='receipt-detail-table']/tbody/tr[1]/td[11]/input").click()
driver.find_element_by_xpath("html/body/div[5]/div[3]/table/tbody/tr[3]/td[4]").click()
driver.find_element_by_xpath(".//*[@id='modal-form-confirm']").click()
time.sleep(2)
driver.find_element_by_xpath(".//*[@id='btn-alert-confirm']").click()
time.sleep(3)
driver.back()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='753']/li[3]/a").click()
time.sleep(3)
driver.find_element_by_xpath(".//*[@id='unVerify-table']/tbody/tr[1]/td[12]/span[2]").click()
time.sleep(1)
driver.find_element_by_xpath(".//*[@id='alert-modal']/div/div/div[3]/span[2]").click()
time.sleep(5)
driver.quit()



